In [1]:
import torch

# Tensors definition

In [4]:
#NUmber
t1 = torch.tensor(4.)
t1

tensor(4.)

In [5]:
t1.dtype

torch.float32

In [6]:
#Vector
t2 = torch.tensor([2,4.,5,6])
t2

tensor([2., 4., 5., 6.])

In [8]:
#matrix
t3 = torch.tensor([[5,6],[7,8],[8,9]])
t3

tensor([[5, 6],
        [7, 8],
        [8, 9]])

In [10]:
# 3-dimensional array
t4 = torch.tensor([
    [[11,12,13],
    [13,14,15]],
    [
        [15,16,17],
        [17,18,19]
    ]
])
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])

In [11]:
t1.shape

torch.Size([])

In [12]:
t2.shape

torch.Size([4])

In [13]:
t3.shape

torch.Size([3, 2])

In [15]:
t4.shape

torch.Size([2, 2, 3])

# Tensors Operations and Gradients

In [16]:
#Create  tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [17]:
#Arithmetic Operations
y = w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [18]:
#Compute derivatives
y.backward()

In [19]:
#Display Gradients
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


# Interoperability with Numpy

In [21]:
import numpy as np

x = np.array([[1,2],[3,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [22]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [23]:
x. dtype, y.dtype

(dtype('float64'), torch.float64)

In [24]:
#Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

# Linear Regression

In [1]:
import numpy as np
import torch

In [2]:
#IMput (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


# Model from scratch

In [5]:
# Weigths and biases
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[ 0.6793, -1.1296,  0.1343],
        [ 0.5718, -1.0571,  0.4682]], requires_grad=True)
tensor([-0.0717, -2.3112], requires_grad=True)


In [6]:
def model(x):
    return x @ w.t() + b

In [11]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[-20.3957, -11.2589],
        [-29.0710, -13.3320],
        [-84.5554, -67.0543],
        [ 25.6077,  27.8845],
        [-52.2460, -31.5593]], grad_fn=<AddBackward0>)


In [10]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


# Loss function

In [16]:
## MSE Loss
def mse(preds,targets):
    diff = preds-targets
    return torch.sum(diff*diff) / diff.numel()

In [17]:
# Compute loss
loss = mse(preds,targets)
print(loss)

tensor(16594.8770, grad_fn=<DivBackward0>)


## Compute gradients

In [18]:
# Compute gradients
loss.backward()

In [19]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[ 0.6793, -1.1296,  0.1343],
        [ 0.5718, -1.0571,  0.4682]], requires_grad=True)
tensor([[ -8729.3301, -11365.9336,  -6573.9009],
        [ -9011.8398, -11431.6973,  -6658.1895]])


In [20]:
print(b)
print(b.grad)

tensor([-0.0717, -2.3112], requires_grad=True)
tensor([-108.3321, -111.0640])


In [21]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])
