In [8]:
import torch

# Tensors definition

In [9]:
#NUmber
t1 = torch.tensor(4.)
t1

tensor(4.)

In [10]:
t1.dtype

torch.float32

In [11]:
#Vector
t2 = torch.tensor([2,4.,5,6])
t2

tensor([2., 4., 5., 6.])

In [12]:
#matrix
t3 = torch.tensor([[5,6],[7,8],[8,9]])
t3

tensor([[5, 6],
        [7, 8],
        [8, 9]])

In [13]:
# 3-dimensional array
t4 = torch.tensor([
    [[11,12,13],
    [13,14,15]],
    [
        [15,16,17],
        [17,18,19]
    ]
])
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])

In [14]:
t1.shape

torch.Size([])

In [15]:
t2.shape

torch.Size([4])

In [16]:
t3.shape

torch.Size([3, 2])

In [17]:
t4.shape

torch.Size([2, 2, 3])

# Tensors Operations and Gradients

In [18]:
#Create  tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [19]:
#Arithmetic Operations
y = w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [20]:
#Compute derivatives
y.backward()

In [21]:
#Display Gradients
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


# Interoperability with Numpy

In [22]:
import numpy as np

x = np.array([[1,2],[3,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [23]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [24]:
x. dtype, y.dtype

(dtype('float64'), torch.float64)

In [25]:
#Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

# Linear Regression

In [26]:
import numpy as np
import torch

In [27]:
#IMput (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [28]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [29]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


# Model from scratch

In [30]:
# Weigths and biases
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-0.1979,  2.1955, -0.7276],
        [-1.5900, -0.6219, -1.9094]], requires_grad=True)
tensor([ 0.9541, -0.4886], requires_grad=True)


In [31]:
def model(x):
    return x @ w.t() + b

In [32]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 102.3200, -240.3293],
        [ 129.5838, -322.1062],
        [ 235.7354, -332.8960],
        [  48.2538, -260.0582],
        [ 147.1361, -303.5574]], grad_fn=<AddBackward0>)


In [33]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


# Loss function

In [34]:
## MSE Loss
def mse(preds,targets):
    diff = preds-targets
    return torch.sum(diff*diff) / diff.numel()

In [35]:
# Compute loss
loss = mse(preds,targets)
print(loss)

tensor(77995.0859, grad_fn=<DivBackward0>)


## Compute gradients

In [36]:
# Compute gradients
loss.backward()

In [37]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-0.1979,  2.1955, -0.7276],
        [-1.5900, -0.6219, -1.9094]], requires_grad=True)
tensor([[  4736.3486,   5677.4673,   3186.5386],
        [-32229.2109, -34758.8984, -21603.0195]])


In [38]:
print(b)
print(b.grad)

tensor([ 0.9541, -0.4886], requires_grad=True)
tensor([  56.4058, -383.7894])


In [39]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


# Adjust weights and biases using gradient descent

In [40]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 102.3200, -240.3293],
        [ 129.5838, -322.1062],
        [ 235.7354, -332.8960],
        [  48.2538, -260.0582],
        [ 147.1361, -303.5574]], grad_fn=<AddBackward0>)


In [41]:
#Calculate the loss
loss = mse(preds,targets)
print(loss)

tensor(77995.0859, grad_fn=<DivBackward0>)


In [42]:
#Cumpute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[  4736.3486,   5677.4673,   3186.5386],
        [-32229.2109, -34758.8984, -21603.0195]])
tensor([  56.4058, -383.7894])


In [43]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad*1e-5
    b -= b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

In [44]:
print(w)
print(b)

tensor([[-0.2453,  2.1388, -0.7595],
        [-1.2677, -0.2743, -1.6934]], requires_grad=True)
tensor([ 0.9536, -0.4848], requires_grad=True)


In [45]:
#Calculate the loss
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor(52697.3828, grad_fn=<DivBackward0>)


In [46]:
# Train for 100 mepochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds,targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad*1e-5
        b -= b.grad*1e-5
        w.grad.zero_()
        b.grad.zero_()

In [47]:
#Calculate the loss
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor(284.2204, grad_fn=<DivBackward0>)


In [48]:
preds

tensor([[ 56.1160,  72.2515],
        [ 68.9152,  90.2382],
        [150.6123, 153.5596],
        [ 12.7898,  47.5764],
        [ 83.8238,  94.7345]], grad_fn=<AddBackward0>)

In [49]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

# Linear regression using Pytorch built-ins

In [50]:
import torch.nn as nn

In [51]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

In [52]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

## Dataset and DataLoader

In [53]:
from torch.utils.data import TensorDataset

In [54]:
#Define dataset
train_ds = TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [55]:
from torch.utils.data import DataLoader

In [56]:
#Define data loader
batch_size = 5
train_dl = DataLoader(train_ds,batch_size,shuffle=True)

In [57]:
for xb,yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[101.,  44.,  37.],
        [ 87., 134.,  58.],
        [103.,  43.,  36.],
        [ 87., 135.,  57.],
        [102.,  43.,  37.]])
tensor([[ 21.,  38.],
        [119., 133.],
        [ 20.,  38.],
        [118., 134.],
        [ 22.,  37.]])


In [59]:
# Define model
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.2467, -0.3208,  0.0877],
        [ 0.1931, -0.2501, -0.2121]], requires_grad=True)
Parameter containing:
tensor([ 0.4751, -0.4026], requires_grad=True)


In [60]:
#Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.2467, -0.3208,  0.0877],
         [ 0.1931, -0.2501, -0.2121]], requires_grad=True),
 Parameter containing:
 tensor([ 0.4751, -0.4026], requires_grad=True)]

In [61]:
#Generate predictions
preds = model(inputs)
preds

tensor([[-35.2562, -12.1792],
        [-44.5919, -18.4082],
        [-58.8899, -29.4139],
        [-35.2358,   0.6972],
        [-41.2057, -25.9307],
        [-35.1820, -11.7359],
        [-44.1834, -18.3701],
        [-59.0488, -29.4328],
        [-35.3099,   0.2540],
        [-40.8713, -26.3359],
        [-34.8477, -12.1411],
        [-44.5178, -17.9649],
        [-59.2984, -29.4520],
        [-35.5701,   1.1024],
        [-41.2799, -26.3740]], grad_fn=<AddmmBackward0>)

## Loss function

In [62]:
#Import nn.functional
import torch.nn.functional as F

In [63]:
#Define loss function
loss_fn = F.mse_loss

In [64]:
loss = loss_fn(model(inputs),targets)
print(loss)

tensor(14925.8896, grad_fn=<MseLossBackward0>)


## Optimizer

In [67]:
#Define the optimizer
opt = torch.optim.SGD(model.parameters(),lr=1e-5)

## Train the model



1. Generate predictions

2. Calculate the loss

3. Compute gradients w.r.t the weights and biases

4. Adjust the weights by subtracting a small quantity proportional to the gradient

5. Reset the gradients to zero


In [68]:
#Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, traind_dl):
    
    #Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        #Train with batches of data
        for xb, yb in train_dl:
            
            #Step 1
            pred = model(xb)
            
            #Step 2
            loss = loss_fn(pred,yb)
            
            #Step 3
            loss.backward()
            
            #Step 4
            opt.step()
            
            #Step 5
            opt.zero_grad()
            
            #Print progress
            if (epoch+1) % 10 == 0:
                print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [70]:
fit(100,model,loss_fn,opt,train_dl)

Epoch [10/100], Loss: 155.4963
Epoch [10/100], Loss: 578.1812
Epoch [10/100], Loss: 809.5983
Epoch [20/100], Loss: 181.6535
Epoch [20/100], Loss: 309.0689
Epoch [20/100], Loss: 575.4058
Epoch [30/100], Loss: 124.5803
Epoch [30/100], Loss: 243.8047
Epoch [30/100], Loss: 375.4824
Epoch [40/100], Loss: 66.4554
Epoch [40/100], Loss: 322.4309
Epoch [40/100], Loss: 127.7738
Epoch [50/100], Loss: 151.0870
Epoch [50/100], Loss: 168.4029
Epoch [50/100], Loss: 69.2442
Epoch [60/100], Loss: 88.2903
Epoch [60/100], Loss: 88.7427
Epoch [60/100], Loss: 87.1485
Epoch [70/100], Loss: 42.1028
Epoch [70/100], Loss: 124.0845
Epoch [70/100], Loss: 33.1998
Epoch [80/100], Loss: 63.1962
Epoch [80/100], Loss: 79.3965
Epoch [80/100], Loss: 7.7731
Epoch [90/100], Loss: 35.4169
Epoch [90/100], Loss: 35.4235
Epoch [90/100], Loss: 48.6359
Epoch [100/100], Loss: 27.5766
Epoch [100/100], Loss: 51.7001
Epoch [100/100], Loss: 19.4297


In [71]:
preds = model(inputs)
preds

tensor([[ 58.2303,  72.0253],
        [ 82.0196,  97.8838],
        [116.5449, 136.2978],
        [ 27.4022,  47.1712],
        [ 98.0627, 108.3020],
        [ 57.1479,  71.0968],
        [ 81.7922,  97.3915],
        [116.8366, 136.6406],
        [ 28.4847,  48.0996],
        [ 98.9177, 108.7382],
        [ 58.0029,  71.5330],
        [ 80.9371,  96.9553],
        [116.7723, 136.7901],
        [ 26.5472,  46.7350],
        [ 99.1452, 109.2305]], grad_fn=<AddmmBackward0>)

In [72]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])